version: '3.1'

services:

  postgres_latest: # https://hub.docker.com/_/postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: db-test
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa
    profiles:
      - pg_latest
    ports:
      - 5432:5432

  postgres: # https://hub.docker.com/_/postgres
    image: postgres:14.1
    restart: always
    environment:
      POSTGRES_DB: db-test
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa
    profiles:
      - pg_14
    ports:
      - 5432:5432