version: '3.1'

services:

  postgres: # https://hub.docker.com/_/postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: db-test
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa
    ports:
      - 5432:5432
