version: '3.1'

services:

  postgres_1: # https://hub.docker.com/_/postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: db-test1
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa
    ports:
      - 5432:5432

  postgres_2: # https://hub.docker.com/_/postgres
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: db-test2
      POSTGRES_USER: sa
      POSTGRES_PASSWORD: sa
    ports:
      - 5433:5432