version: '3.8'

services:
  grafana:
    image: grafana/grafana:10.2.4
    restart: unless-stopped
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana

  loki:
    image: grafana/loki:2.9.4
    restart: unless-stopped
    container_name: loki
    ports:
      - 3100:3100