version: '3.8'

services:
  grafana:
    image: grafana/grafana:10.2.4
    restart: unless-stopped
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana

  loki:
    image: grafana/loki:2.9.4
    restart: unless-stopped
    container_name: loki
    ports:
      - 3100:3100

  tempo:
    image: grafana/tempo:2.3.1
    restart: unless-stopped
    command: ["--config.file=/etc/tempo.yaml"]
    container_name: tempo
    ports:
      - 3200:3200 # tempo
      - 9095:9095 # tempo grpc
      - 4317:4317 # otlp grpc
      - 4318:4318 # otlp http
      - 9411:9411 # zipkin
      - 14268:14268 # jaeger ingest
    volumes:
      - ./tempo/tempo.yaml:/etc/tempo.yaml