spring:
  application:
    name: server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/RuSichPT/config-repo
          clone-on-start: true
  security:
    user:
      password: root
      name: root
server:
  port: 8888